import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Free-Mercato",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className="flex h-16 bg-yellow-300 px-4">
          <form action="/items" className="m-auto flex max-w-screen-xl flex-1 gap-4">
            <input className="h-8 flex-1 px-2 text-white" type="text" name="search" />
            <button className="h-8 bg-gray-200 px-2 py-1 text-slate-700">
              Buscar
            </button>
          </form>
        </header>
        <main className="max-w-screen-xl p-4">{children}</main>
      </body>
    </html>
  );
}
